ALL=mandelbrot
VCPDIR=..
RM=rm -f
SO=$(VCPDIR)/libvulcmp.so
GLSLC=glslc
RESULTS=mandelbrot.bmp mandelbrot.spv
CC=gcc -g -I$(VCPDIR) -L$(VCPDIR)

all: $(SO) $(ALL:=.run)

%.run: %
	LD_LIBRARY_PATH=$(VCPDIR) ./$<

mandelbrot: mandelbrot.c simplebmp.c mandelbrot.spv
	$(CC) -o $@ mandelbrot.c simplebmp.c -lvulcmp

atom: atom.c atom.spv
	$(CC) -o $@ $< -lvulcmp

chain: chain.c chain.spv
	$(CC) -o $@ $< -lvulcmp

%.spv: %.comp
	$(GLSLC) -o $@ $<

clean:
	$(RM) $(ALL) $(RESULTS) *.spv
