make {

   init {
      $all := ["mandelbrot","pmandelbrot"];
      $vd := "..";
      $C := tool("C",{});
      $Cpp := tool("Cpp",{});
   }

   target {
      
      test {
         build();
         run();
      }

      build() {
         buildMandel();
         buildPMandel();
      }

      run() {
         foreach(i|changeExt($all,exeExt()))
            exec(i);
      }

   }



RM=rm -f
SO=$(VCPDIR)/libvulcmp.so
GLSLC=glslc
RESULTS=mandelbrot.bmp mandelbrot.spv
CC=gcc -g -I$(VCPDIR) -L$(VCPDIR)

all: $(SO) $(ALL:=.run)

%.run: %
	LD_LIBRARY_PATH=$(VCPDIR) ./$<

mandelbrot: mandelbrot.c simplebmp.c mandelbrot.spv
	$(CC) -o $@ mandelbrot.c simplebmp.c -lvulcmp



%.spv: %.comp
	$(GLSLC) -o $@ $<

clean:
	$(RM) $(ALL) $(RESULTS) *.spv
