!include ..\Makefile.defs

VKPATH=$(VK_SDK_PATH)
VCMP=..\vulcmp.obj

CC=cl -I..
LN=link /LIBPATH:"$(LIB)"
RM=del /q

ALL=mandelbrot.exe
GLSLC=$(VKPATH)\Bin\glslc.exe
RESULTS=mandelbrot.bmp mandelbrot.cmp

run: $(ALL)
	mandelbrot.exe

mandelbrot.exe: mandelbrot.c simplebmp.c mandelbrot.spv
	$(CC) mandelbrot.c simplebmp.c $(VCMP) $(VKPATH)\Lib\vulkan-1.lib

mandelbrot.spv: mandelbrot.comp
	$(GLSLC) -o $@ mandelbrot.comp

clean:
	$(RM) $(ALL) $(RESULTS)

