include Makefile.defs

CC=gcc
RM=rm -f

MLIN=make -f Makefile.linux
MDEB=make
LIB=lib$(NAME).so

build: $(LIB)

clean:
	$(RM) $(LIB) *.o
	cd test && $(MLIN) clean
	cd debian && $(MDEB) clean

test: build
	cd test && $(MLIN)

debian: build
	cd debian && $(MDEB)

%.o: %.c %.h
	$(CC) -c -fPIC -Wall -o $@ $<

$(LIB): vulcmp.o
	$(CC) -shared -o $@ $^ -lvulkan

.PHONY: test
