!include Makefile.defs

VKPATH=$(VK_SDK_PATH)
CCARGS=-I$(VKPATH)\Include

CC=cl $(CCARGS)
LN=link /dll /LIBPATH:"$(LIB)"
RM=del /q

MMSVC=nmake /f Makefile.msvc
MDEB=make
VLIB=$(NAME).dll

build: $(VLIB)

clean:
	$(RM) $(VLIB) *.obj
	cd test
	$(MMSVC) clean

test: build
	cd test
	$(MMSVC)

{$S}.c{$O}.obj:
	$(CC) -c $O $<

$(VLIB): vulcmp.obj
	$(LN) vulcmp.obj $(VKPATH)\Lib\vulkan-1.lib

.PHONY: test
